- name: Create Ubuntu 24.04 Cloud-Init Template from existing image
  hosts: proxmox
  become: true

  vars:
    # --- Template Configuration ---
    template_vmid: 9000 # 使用一个高的、固定的ID作为模板ID
    template_name: "ubuntu-2404-cloud-template"
    template_memory: 2048
    template_cores: 2
    template_storage: "local-lvm" # 模板的虚拟磁盘将存放在此

    # --- Image Source ---
    image_name: "ubuntu-24.04-noble-cloudimg.img"
    # !! 重要: 这个路径必须与 'download-cloud-image.yaml' 中的 'image_dest_path' 完全匹配
    image_source_path: "/mnt/pve/iso-templates/template/iso/{{ image_name }}"

  tasks:
    - name: Check if template already exists
      ansible.builtin.command: "qm status {{ template_vmid }}"
      register: template_check
      failed_when: false # 即使命令失败（模板不存在）也不要报错
      changed_when: false

    - name: Stop if template already exists
      ansible.builtin.meta: end_play
      when: template_check.rc == 0

    - name: Check if the source image exists
      ansible.builtin.stat:
        path: "{{ image_source_path }}"
      register: image_file

    - name: Fail if source image is not found
      ansible.builtin.fail:
        msg: >
          Source image not found at {{ image_source_path }}.
          Please run the 'download-cloud-image' task first.
      when: not image_file.stat.exists

    # --- Block for creating the template ---
    - name: Create a new template from the existing image
      block:
        - name: Create a new temporary VM
          ansible.builtin.command: >
            qm create {{ template_vmid }} --name {{ template_name }}-builder --memory {{ template_memory }}
            --cores {{ template_cores }} --net0 virtio,bridge=vmbr0 --scsihw virtio-scsi-pci
          changed_when: true

        - name: Import the disk from the existing image
          ansible.builtin.command: >
            qm importdisk {{ template_vmid }} {{ image_source_path }} {{ template_storage }}
          changed_when: true

        - name: Attach the new disk to the VM as scsi0
          ansible.builtin.command: >
            qm set {{ template_vmid }} --scsi0 {{ template_storage }}:vm-{{ template_vmid }}-disk-0,discard=on
          changed_when: true

        - name: Add Cloud-Init CD-ROM drive
          ansible.builtin.command: >
            qm set {{ template_vmid }} --ide2 {{ template_storage }}:cloudinit
          changed_when: true

        - name: Set boot order to boot from the new disk
          ansible.builtin.command: >
            qm set {{ template_vmid }} --boot c --bootdisk scsi0
          changed_when: true

        - name: Add a serial console for debugging
          ansible.builtin.command: >
            qm set {{ template_vmid }} --serial0 socket --vga serial0
          changed_when: true

        - name: Convert the VM to a template
          ansible.builtin.command: "qm template {{ template_vmid }}"
          changed_when: true
      when: template_check.rc != 0