---
- name: Turn off console screen on Proxmox host
  hosts: pve-1
  gather_facts: false
  tasks:
    - name: Turn off laptop screen via setterm on tty1
      ansible.builtin.shell:
        cmd: >
          TERM=linux setterm --blank poke < /dev/tty1 > /dev/tty1 &&
          TERM=linux setterm --blank force < /dev/tty1 > /dev/tty1
      changed_when: true
