- name: Download Ubuntu 26.04 cloud image to Proxmox
  hosts: proxmox
  become: true
  tasks:
    - name: Download Ubuntu 26.04 cloud image
      ansible.builtin.get_url:
        url: https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img
        dest: /var/lib/vz/template/iso/ubuntu-26.04-cloudimg-amd64.img
        mode: "0644"
