apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-bench
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  source:
    repoURL: https://github.com/meirongdev/homelab
    targetRevision: main
    path: k8s/helm/manifests
    directory:
      include: "kube-bench.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-bench
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false   # Namespace 由 manifest 自身渲染
      - ServerSideApply=true
