apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oracle-k3s
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab

  source:
    repoURL: https://github.com/meirongdev/homelab
    targetRevision: main
    path: cloud/oracle/manifests

  destination:
    server: https://100.107.166.37:6443 # oracle-k3s API Server via Tailscale
    namespace: kube-system # Destination namespace doesn't strictly matter for Kustomize apps with explicit namespaces

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
