apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-eso
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab

  source:
    repoURL: https://github.com/meirongdev/homelab
    targetRevision: main
    path: k8s/helm/manifests
    directory:
      include: "{vault-eso-config.yaml,cloudflare-external-secret.yaml,grafana-external-secret.yaml,postgres-external-secret.yaml,stirling-pdf-external-secret.yaml}"

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  # ESO controller adds default values to remoteRef and target fields
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.data[].remoteRef.conversionStrategy
        - .spec.data[].remoteRef.decodingStrategy
        - .spec.data[].remoteRef.metadataPolicy
        - .spec.target.deletionPolicy
